version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=localdev
      - POSTGRES_PASSWORD=localdev
      - POSTGRES_DB=localdev
    volumes:
      - "./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          memory: 256M
  keycloak:
    image: bitnami/keycloak:20.0.1
    restart: unless-stopped
    environment:
      - KEYCLOAK_DATABASE_HOST=db
      - KEYCLOAK_DATABASE_NAME=localdev
      - KEYCLOAK_DATABASE_USER=localdev
      - KEYCLOAK_DATABASE_PASSWORD=localdev
      - KEYCLOAK_DATABASE_SCHEMA=keycloak
      - KEYCLOAK_ENABLE_STATISTICS=true
    ports:
      - '8080:8080'
      - '8443:8443'
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 512M
  app:
    image: bareplay:1.0-SNAPSHOT
    restart: unless-stopped
    environment:
      - APPLICATION_DB_DEFAULT_URL=jdbc:postgresql://db:5432/localdev
      - APPLICATION_DB_DEFAULT_USERNAME=localdev
      - APPLICATION_DB_DEFAULT_PASSWORD=localdev
    ports:
      - '9000:9000'
    depends_on:
      - keycloak
      - db
    deploy:
      resources:
        limits:
          memory: 256M
