version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db
    volumes:
      - "./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          memory: 256M
  keycloak:
    image: quay.io/keycloak/keycloak:21.0
    restart: unless-stopped
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/db
      - KC_DB_USERNAME=db
      - KC_DB_PASSWORD=db
    ports:
      - '8080:8080'
      - '8443:8443'
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 512M
    command:
      - start-dev
  app:
    image: bareplay:1.0-SNAPSHOT
    restart: unless-stopped
    environment:
      - APPLICATIONNAME_DB_DEFAULT_URL=jdbc:postgresql://db:5432/db
      - APPLICATIONNAME_DB_DEFAULT_USERNAME=db
      - APPLICATIONNAME_DB_DEFAULT_PASSWORD=db
    ports:
      - '9000:9000'
    depends_on:
      - keycloak
      - db
    deploy:
      resources:
        limits:
          memory: 256M
    command:
      - -J-XX:MaxRAM=150m
      - -J-XX:+UseSerialGC
      - -J-XX:+TieredCompilation
      - -J-XX:TieredStopAtLevel=1
