create table access_counter
(
    id          bigint generated by default as identity primary key,
    counter     bigint                   not null default 0,
    last_update timestamp with time zone not null default now()
);
